# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb7a7c65949bab3bdc6144fbe80c3ed119569f45bd26247fd23c0f85a7975243d9294ba6808d918e7fa01d158f2b00ed143060c1fb2ede11d28c659fb70d23f7

test:
  secret_key_base: e03055c6f65123a2ed6f19e45c6cdda02d4fddd04821b83a15320c80beaadb404152f6041ee70dc752fc6da524bf00ab452b8493d101646dfe1b2a6daed73187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
